### ISSUE TITLE
`eosio.msig::approve` permission is dangerous running in server side scripts

### ISSUE THREAD

**Issue by DenisCarriere** [EOSLaoMao/bp-kicking-proposal-monitor#7]
Giving any server side scripts permission to `eosio.msig::approve` is dangerous.

Anyone having access to that server side private key would be able to have 100% full access to the `@active` permission of the BP.

Note: You cannot execute `eosio.msig::approve` using a sub permission if the MSIG is requiring `@active` permission. This means that an additional private key needs to have 100% weight of the block producer account and that key is sitting un-encrypted on a server side application.

**Comment by JohnnyZhao** [comment]
Hi Denis, you might want to take a closer look.

The eosio.msig::approve is only used to craft a transaction payload which is not signed(so no keys needed) and only used for later proposal as packed_tx. 

So there's no need to provide any secret key or account related to your BP account.

This tool only propose a proposal for your BP account using a total different account, say eoslaomaoxxx, and then as a BP operator like you, you can use your BP key to approve this proposal or not, and so does your other teammates who has control of your msig-ed BP account.

And the content of this proposal you approved is to approve the actual kicking proposal proposed by Aloha EOS Mainnet Tracker. 

So, I think the name 'auto kicker' is miss-leading here. What it does actually is 'auto propose a proposal that approves the kicking proposal(by Aloha EOS Mainnet Tracker) use a total different account and wait for you and your teammates to approve it as your BP account is msig-ed'.

Once enough approvals reached, anyone can executed this proposal, which will approve the kicking proposal.

So, it's actually a semi-automatic manner.

**Comment by JohnnyZhao** [comment]
The post above I think invalidates other two issues, too.

**Comment by DenisCarriere** [comment]
Ah, I get it now.

So it creates an automatic MSIG for you to approve another proposal 

In that case, yes the title and description is very misleading 😂
